-- MySQL Script generated by MySQL Workbench
-- mer 10 ott 2018 17:25:56 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gpg_keyserver
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gpg_keyserver
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gpg_keyserver` ;
USE `gpg_keyserver` ;

-- -----------------------------------------------------
-- Table `gpg_keyserver`.`ptree`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpg_keyserver`.`ptree` (
  `node_key` VARCHAR(250) NOT NULL,
  `node_svalues` BLOB NOT NULL,
  `num_elements` INT NOT NULL,
  `leaf` TINYINT(1) NOT NULL,
  `node_elements` BLOB NOT NULL,
  PRIMARY KEY (`node_key`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gpg_keyserver`.`RSAPubKey`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpg_keyserver`.`RSAPubKey` (
  `id` INT NOT NULL,
  `n` BLOB NOT NULL,
  `e` BLOB NOT NULL,
  `p` BLOB NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gpg_keyserver`.`DSAPubKey`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpg_keyserver`.`DSAPubKey` (
  `id` INT NOT NULL,
  `p` BLOB NOT NULL,
  `q` BLOB NOT NULL,
  `g` BLOB NOT NULL,
  `y` BLOB NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gpg_keyserver`.`EGLPubKey`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpg_keyserver`.`EGLPubKey` (
  `id` INT NOT NULL,
  `y` BLOB NOT NULL,
  `e` BLOB NOT NULL,
  `p` BLOB NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gpg_keyserver`.`ECDSAPubKey`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpg_keyserver`.`ECDSAPubKey` (
  `id` INT NOT NULL,
  `curveOID` LONGTEXT NOT NULL,
  `q` BLOB NOT NULL,
  `n` BLOB NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gpg_keyserver`.`broken_keys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpg_keyserver`.`broken_keys` (
  `id` INT(11) NOT NULL,
  `certificate` LONGBLOB NULL DEFAULT NULL,
  `log` VARCHAR(500) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gpg_keyserver`.`gpg_keyserver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpg_keyserver`.`gpg_keyserver` (
  `version` TINYINT(3) UNSIGNED NOT NULL,
  `ID` BIGINT(20) UNSIGNED NOT NULL,
  `fingerprint` BINARY(20) NOT NULL,
  `certificate` LONGBLOB NULL DEFAULT NULL,
  `hash` VARCHAR(128) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `is_unpacked` TINYINT(4) NOT NULL DEFAULT '0',
  `is_synchronized` TINYINT(4) NOT NULL DEFAULT '0',
  `error_code` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`version`, `fingerprint`),
  INDEX `ID` USING BTREE (`ID` ASC, `fingerprint` ASC),
  INDEX `index3` (`hash` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gpg_keyserver`.`KeyStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpg_keyserver`.`KeyStatus` (
  `version` TINYINT(3) UNSIGNED NOT NULL,
  `fingerprint` BINARY(20) NOT NULL,
  `vulnerabilityCode` TINYINT(4) NOT NULL,
  `vulnerabilityDescription` VARCHAR(250) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`version`, `fingerprint`, `vulnerabilityCode`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gpg_keyserver`.`Pubkey`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpg_keyserver`.`Pubkey` (
  `keyId` BIGINT(20) UNSIGNED NOT NULL,
  `version` TINYINT(3) UNSIGNED NOT NULL,
  `fingerprint` BINARY(20) NOT NULL,
  `PriFingerprint` BINARY(20) NULL DEFAULT NULL,
  `pubAlgorithm` SMALLINT(5) UNSIGNED NOT NULL,
  `creationTime` DATETIME NOT NULL,
  `expirationTime` DATETIME NULL DEFAULT NULL,
  `revocationTime` DATETIME NULL DEFAULT NULL,
  `e` BLOB NULL DEFAULT NULL,
  `n` BLOB NULL DEFAULT NULL,
  `p` BLOB NULL DEFAULT NULL,
  `q` BLOB NULL DEFAULT NULL,
  `g` BLOB NULL DEFAULT NULL,
  `y` BLOB NULL DEFAULT NULL,
  `curveOID` TEXT COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `is_analyzed` TINYINT(4) NOT NULL DEFAULT '0',
  `sccIndex` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`version`, `fingerprint`),
  INDEX `n` (`n`(200) ASC),
  INDEX `p` (`p`(200) ASC),
  INDEX `q` (`q`(200) ASC),
  INDEX `y` (`y`(200) ASC),
  INDEX `sccIndex` (`sccIndex` ASC),
  INDEX `keyId` USING BTREE (`keyId` ASC, `fingerprint` ASC),
  INDEX `fingerprint` (`fingerprint` ASC),
  INDEX `Pubkey_cert` (`version` ASC, `PriFingerprint` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gpg_keyserver`.`removed_hash`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpg_keyserver`.`removed_hash` (
  `hash` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`hash`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gpg_keyserver`.`selfSignaturesMetadata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpg_keyserver`.`selfSignaturesMetadata` (
  `id` INT(10) UNSIGNED NOT NULL,
  `type` SMALLINT(5) UNSIGNED NOT NULL,
  `pubAlgorithm` SMALLINT(5) UNSIGNED NOT NULL,
  `hashAlgorithm` SMALLINT(5) UNSIGNED NOT NULL,
  `version` SMALLINT(5) UNSIGNED NOT NULL,
  `issuingKeyId` BIGINT(20) UNSIGNED NOT NULL,
  `issuingFingerprint` BINARY(20) NOT NULL,
  `preferedHash` BLOB NULL DEFAULT NULL,
  `preferedCompression` BLOB NULL DEFAULT NULL,
  `preferedSymmetric` BLOB NULL DEFAULT NULL,
  `trustLevel` SMALLINT(5) UNSIGNED NULL DEFAULT NULL,
  `keyExpirationTime` DATETIME NULL DEFAULT NULL,
  `isPrimaryUserId` TINYINT(1) NOT NULL,
  `signedUserId` VARCHAR(750) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `userRole` VARCHAR(40) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `type` (`type` ASC),
  INDEX `hashAlgorithm` (`hashAlgorithm` ASC),
  INDEX `issuingKey` USING BTREE (`issuingKeyId` ASC, `issuingFingerprint` ASC),
  INDEX `issuingFingerprint` (`issuingFingerprint` ASC, `signedUserId`(200) ASC),
  INDEX `signedUserId` (`signedUserId`(200) ASC),
  INDEX `version` (`version` ASC, `issuingFingerprint` ASC, `trustLevel` ASC, `isPrimaryUserId` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gpg_keyserver`.`Signatures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpg_keyserver`.`Signatures` (
  `id` INT(10) UNSIGNED NOT NULL,
  `type` SMALLINT(5) UNSIGNED NOT NULL,
  `pubAlgorithm` SMALLINT(5) UNSIGNED NOT NULL,
  `hashAlgorithm` SMALLINT(5) UNSIGNED NOT NULL,
  `version` SMALLINT(5) UNSIGNED NOT NULL,
  `issuingKeyId` BIGINT(20) UNSIGNED NOT NULL,
  `signedKeyId` BIGINT(20) UNSIGNED NOT NULL,
  `issuingFingerprint` BINARY(20) NULL DEFAULT NULL,
  `signedFingerprint` BINARY(20) NOT NULL,
  `signedUsername` VARCHAR(750) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `sign_Uatt_id` INT(11) NULL DEFAULT NULL,
  `issuingUsername` VARCHAR(750) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `regex` VARCHAR(40) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `creationTime` DATETIME NOT NULL,
  `expirationTime` DATETIME NULL DEFAULT NULL,
  `r` BLOB NULL DEFAULT NULL,
  `s` BLOB NULL DEFAULT NULL,
  `flags` BLOB NULL DEFAULT NULL,
  `hashHeader` BINARY(2) NULL DEFAULT NULL,
  `signedHash` BLOB NULL DEFAULT NULL,
  `hashMismatch` TINYINT(4) NULL DEFAULT '0',
  `keyExpirationTime` DATETIME NULL DEFAULT NULL,
  `revocationCode` SMALLINT(5) UNSIGNED NULL DEFAULT NULL,
  `revocationReason` VARCHAR(500) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `revocationSigId` INT(10) UNSIGNED NULL DEFAULT NULL,
  `isRevocable` TINYINT(4) NOT NULL DEFAULT '1',
  `isExportable` TINYINT(1) NOT NULL,
  `isExpired` TINYINT(4) NOT NULL DEFAULT '0',
  `isValid` TINYINT(4) NOT NULL DEFAULT '0',
  `isRevocation` TINYINT(4) NOT NULL DEFAULT '0',
  `is_analyzed` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `r_2` USING BTREE (`r`(200) ASC, `s`(200) ASC),
  INDEX `type` (`type` ASC),
  INDEX `hashAlgorithm` (`hashAlgorithm` ASC),
  INDEX `issuingKeyId` (`issuingKeyId` ASC),
  INDEX `signedKeyId` (`signedKeyId` ASC),
  INDEX `issuingFingerprint` (`issuingFingerprint` ASC),
  INDEX `signedFingerprint` (`signedFingerprint` ASC),
  INDEX `r` (`r`(200) ASC),
  INDEX `s` (`s`(200) ASC),
  INDEX `Unique_index` USING BTREE (`issuingKeyId` ASC, `signedKeyId` ASC, `signedUsername`(255) ASC, `creationTime` ASC),
  INDEX `version` (`version` ASC),
  INDEX `signed_key` (`signedKeyId` ASC, `signedFingerprint` ASC),
  INDEX `issuing_key` (`issuingKeyId` ASC, `issuingFingerprint` ASC),
  INDEX `issuing_uid` (`issuingUsername`(255) ASC),
  INDEX `signed_uid` (`signedUsername`(255) ASC),
  INDEX `sign_Uatt_id` USING BTREE (`sign_Uatt_id` ASC, `signedFingerprint` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gpg_keyserver`.`SignatureStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpg_keyserver`.`SignatureStatus` (
  `signature_id` INT(10) UNSIGNED NOT NULL,
  `vulnerabilityCode` TINYINT(4) NOT NULL,
  `vulnerabilityDescription` VARCHAR(250) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`signature_id`, `vulnerabilityCode`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gpg_keyserver`.`Unpacker_errors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpg_keyserver`.`Unpacker_errors` (
  `idx` INT(11) NOT NULL,
  `version` TINYINT(3) UNSIGNED NOT NULL,
  `fingerprint` BINARY(20) NOT NULL,
  `error` TEXT COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  PRIMARY KEY (`idx`),
  INDEX `external key` USING BTREE (`version` ASC, `fingerprint` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gpg_keyserver`.`UserAttribute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpg_keyserver`.`UserAttribute` (
  `id` INT(11) NOT NULL,
  `fingerprint` BINARY(20) NOT NULL,
  `name` VARCHAR(750) CHARACTER SET 'utf8' NOT NULL,
  `encoding` INT(11) NULL DEFAULT NULL,
  `image` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `fingerprint`, `name`(200)),
  UNIQUE INDEX `fingerprint` USING BTREE (`fingerprint`(10) ASC, `name`(200) ASC, `image`(60) ASC),
  INDEX `userID` (`fingerprint` ASC, `name`(200) ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gpg_keyserver`.`UserID`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpg_keyserver`.`UserID` (
  `ownerkeyID` BIGINT(20) UNSIGNED NOT NULL,
  `fingerprint` BINARY(20) NOT NULL,
  `name` VARCHAR(750) CHARACTER SET 'utf8' NOT NULL,
  `email` VARCHAR(500) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `is_analyze` TINYINT(4) NULL DEFAULT NULL,
  `bindingAuthentic` TINYINT(4) NOT NULL,
  PRIMARY KEY USING BTREE (`fingerprint`, `name`(200)),
  INDEX `ownerkeyID` (`ownerkeyID` ASC, `fingerprint` ASC),
  INDEX `name` (`name`(200) ASC))
ENGINE = InnoDB;

USE `gpg_keyserver` ;

-- -----------------------------------------------------
-- Placeholder table for view `gpg_keyserver`.`key_primary_userID`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpg_keyserver`.`key_primary_userID` (`id` INT);

-- -----------------------------------------------------
-- Placeholder table for view `gpg_keyserver`.`Signature_no_issuing_fp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpg_keyserver`.`Signature_no_issuing_fp` (`id` INT);

-- -----------------------------------------------------
-- View `gpg_keyserver`.`key_primary_userID`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gpg_keyserver`.`key_primary_userID`;
USE `gpg_keyserver`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `key_primary_userID`  AS  (select `selfSignaturesMetadata`.`version` AS `version`,`selfSignaturesMetadata`.`issuingFingerprint` AS `fingerprint`,`selfSignaturesMetadata`.`signedUserId` AS `name`,`selfSignaturesMetadata`.`isPrimaryUserId` AS `isPrimaryUserId`,`selfSignaturesMetadata`.`trustLevel` AS `trustLevel` from `selfSignaturesMetadata` group by `selfSignaturesMetadata`.`version`,`selfSignaturesMetadata`.`issuingFingerprint` order by `selfSignaturesMetadata`.`isPrimaryUserId` desc,`selfSignaturesMetadata`.`trustLevel` desc);

-- -----------------------------------------------------
-- View `gpg_keyserver`.`Signature_no_issuing_fp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gpg_keyserver`.`Signature_no_issuing_fp`;
USE `gpg_keyserver`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `Signature_no_issuing_fp`  AS  (select `Signatures`.`id` AS `id`,`Pubkey`.`fingerprint` AS `fp` from (`Signatures` join `Pubkey` on((`Signatures`.`issuingKeyId` = `Pubkey`.`keyId`))) where (`Signatures`.`issuingFingerprint` = NULL));
USE `gpg_keyserver`;

DELIMITER $$
USE `gpg_keyserver`$$
CREATE TRIGGER `save_hash` AFTER UPDATE ON `gpg_keyserver` FOR EACH ROW IF (OLD.is_synchronized = 1 and OLD.hash != NEW.hash) THEN
            INSERT IGNORE INTO removed_hash VALUES(OLD.hash);
      END IF$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
